images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "0.12.0"
- name: cloud-controller-manager
  sourceRepository: https://github.com/packethost/packet-ccm
  repository: docker.io/packethost/packet-ccm
  tag: "d0abe6c"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
# The machine-controller-manager contains a fix in commit 67239235d15eb3d8d0b384bb1ff4067ae5b0e153 for Packet which is required.
# However, there is not yet a new release of MCM. Thus, we keep referencing the latest MCM (0.18.0) without the fix to make the
# component descriptor work properly. The Packet worker controller, however, requires the mentioned fix to function properly.
# tag: "0.19.0-dev-67239235d15eb3d8d0b384bb1ff4067ae5b0e153"
  tag: "0.18.0"
