images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "0.13.0"
- name: cloud-controller-manager
  sourceRepository: https://github.com/packethost/packet-ccm
  repository: docker.io/packethost/packet-ccm
  tag: "d0abe6c"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
# The machine-controller-manager contains a fix in commit 67239235d15eb3d8d0b384bb1ff4067ae5b0e153 for Packet which is required.
# However, there is not yet a new release of MCM. Thus, we keep referencing the latest MCM (0.18.0) without the fix to make the
# component descriptor work properly. The Packet worker controller, however, requires the mentioned fix to function properly.
# tag: "0.19.0-dev-67239235d15eb3d8d0b384bb1ff4067ae5b0e153"
  tag: "0.18.0"
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.0.1
  runtimeVersion: 1.13.x
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.1.0
  runtimeVersion: 1.14.x
- name: packet-storage-interface
  sourceRepository: https://github.com/packethost/csi-packet
  repository: docker.io/packethost/csi-packet
  tag: "73641b0"
