images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer
  tag: "0.12.0"
- name: cloud-controller-manager
  sourceRepository: https://github.com/packethost/packet-ccm
  repository: docker.io/packethost/packet-ccm
  tag: "16d53b6"
