apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-provider-alicloud-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-provider-alicloud
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    ---
    apiVersion: alicloud.provider.extensions.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration
{{- if .Values.config.machineImages }}
    machineImages:
{{ toYaml .Values.config.machineImages | indent 4 }}
{{- end }}
