{{- if eq .Values.gardener.seed.provider "alicloud" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
provisioner: diskplugin.csi.alibabacloud.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: cloud_ssd
  readOnly: false
{{- end }}
