---
apiVersion: gcp.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
machineImages:
- name: coreos
  version: 2023.5.0
  image: projects/coreos-cloud/global/images/coreos-stable-2023-5-0-v20190312
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 25Gi
  backup:
    schedule: "0 */24 * * *"
