apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-provider-openstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-provider-openstack
    helm.sh/chart: gardener-extension-provider-openstack
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-provider-openstack
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap-gardener-extension-provider-openstack-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: gardener-extension-provider-openstack
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-provider-openstack
      containers:
      - name: gardener-extension-provider-openstack
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - provider-openstack-controller-manager
        - --config-file=/etc/gardener-extension-provider-openstack/config/config.yaml
        - --infrastructure-max-concurrent-reconciles={{ .Values.controllers.infrastructure.concurrentSyncs }}
        - --infrastructure-ignore-operation-annotation={{ .Values.controllers.infrastructure.ignoreOperationAnnotation }}
        - --worker-max-concurrent-reconciles={{ .Values.controllers.worker.concurrentSyncs }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/gardener-extension-provider-openstack/config
      volumes:
      - name: config
        configMap:
          name: gardener-extension-provider-openstack-configmap
          defaultMode: 420
