apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-provider-openstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-provider-openstack
    helm.sh/chart: gardener-extension-provider-openstack
    app.kubernetes.io/instance: {{ .Release.Name }}
