apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-provider-aws
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-provider-aws
    helm.sh/chart: gardener-extension-provider-aws
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-provider-aws
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap-gardener-extension-provider-aws-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: gardener-extension-provider-aws
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-provider-aws
      containers:
      - name: gardener-extension-provider-aws
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - provider-aws-controller-manager
        - --config-file=/etc/gardener-extension-provider-aws/config/config.yaml
        - --controlplane-max-concurrent-reconciles={{ .Values.controllers.controlplane.concurrentSyncs }}
        - --infrastructure-max-concurrent-reconciles={{ .Values.controllers.infrastructure.concurrentSyncs }}
        {{- if .Values.controllers.infrastructure.ignoreOperationAnnotation }}
        - --infrastructure-ignore-operation-annotation={{ .Values.controllers.infrastructure.ignoreOperationAnnotation }}
        {{- end }}
        - --webhook-config-mode=service
        - --webhook-config-name=aws-webhooks
        - --webhook-config-namespace={{ .Release.Namespace }}
        - --webhook-config-service-selectors={"app.kubernetes.io/name":"gardener-extension-provider-aws","app.kubernetes.io/instance":"{{ .Release.Name }}"}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: webhook-server
          containerPort: 7890
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/gardener-extension-provider-aws/config
        - name: cert
          mountPath: /tmp/cert
      volumes:
      - name: config
        configMap:
          name: gardener-extension-provider-aws-configmap
          defaultMode: 420
      - name: cert
        secret:
          secretName: aws-webhooks
          defaultMode: 420
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-webhooks
  namespace: {{ .Release.Namespace }}
