---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-provider-aws
  labels:
    app.kubernetes.io/name: gardener-extension-provider-aws
    helm.sh/chart: gardener-extension-provider-aws
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  - infrastructures
  - infrastructures/status
  - controlplanes
  - controlplanes/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - provider-aws-leader-election
  verbs:
  - get
  - watch
  - update
  - patch
- apiGroups:
  - ""
  - batch
  - rbac.authorization.k8s.io
  - admissionregistration.k8s.io
  resources:
  - events
  - secrets
  - configmaps
  - services
  - serviceaccounts
  - roles
  - rolebindings
  - jobs
  - pods
  - pods/log
  - mutatingwebhookconfigurations
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-extension-provider-aws
  labels:
    app.kubernetes.io/name: gardener-extension-provider-aws
    helm.sh/chart: gardener-extension-provider-aws
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-extension-provider-aws
subjects:
- kind: ServiceAccount
  name: gardener-extension-provider-aws
  namespace: {{ .Release.Namespace }}
