apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  config.yaml: |
    ---
    apiVersion: packet.provider.extensions.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration
{{- if .Values.config.machineImages }}
    machineImages:
{{ toYaml .Values.config.machineImages | indent 4 }}
{{- end }}
