apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-worker-config
  namespace: {{ .Release.Namespace }}
data:
  cloudprovider.conf: |
    {{- include "cloud-provider-config.common" . }}
    {{- if semverCompare "< 1.15" .Values.kubernetesVersion }}
    aadClientId: "{{ .Values.aadClientId }}"
    aadClientSecret: "{{ .Values.aadClientSecret }}"
    tenantId: "{{ .Values.tenantId }}"
    subscriptionId: "{{ .Values.subscriptionId }}"
    {{- else }}
    useInstanceMetadata: true
    {{- end}}