---
apiVersion: certificate-service.extensions.config.gardener.cloud/v1alpha1
kind: Configuration
spec:
  lifecycleSync: "1h"
  serviceSync: "5m"
  issuerName: lets-encrypt
  namespaceRef: default
  resourceNamespace: garden
  acme:
    email: john.doe@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
  # privateKey: | # Optional key for Let's Encrypt account.
  #   -----BEGIN BEGIN RSA PRIVATE KEY-----
  #   ...
  #   -----END RSA PRIVATE KEY-----
  providers:
    cloudDNS:
    - name: clouddns-prod
      domains:
      - example.io
      project: project_id
      serviceAccount: |
        {
        "type": "service_account",
        "project_id": "demo-project"
        }
    route53:
    - name: route53-prod
      domains:
      - example.com
      region: us-east-1
      accessKeyID: your-accessKeyID
      secretAccessKey: your-secretAccessKey
