openstack:
  authURL: https://keystone/v3/
  domainName: CP
  tenantName: kubernetes
  region: eu-de-1
  floatingPoolName: my-pool

create:
  router: true

sshPublicKey: sshkey-12345

router:
  id: ${openstack_networking_router_v2.router.id}

dnsServers:
- 8.8.8.8

clusterName: test-namespace

networks:
  worker: 10.250.0.0/19

outputKeys:
  routerId: router_id
  networkId: network_id
  keyName: key_name
  securityGroupId: security_group_id
  securityGroupName: security_group_name
  floatingNetworkId: floating_network_id
  subnetId: subnet_id