apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-provider-gcp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-provider-gcp
    helm.sh/chart: gardener-extension-provider-gcp
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-provider-gcp
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap-gardener-extension-provider-gcp-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: gardener-extension-provider-gcp
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-provider-gcp
      containers:
      - name: gardener-extension-provider-gcp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - provider-gcp-controller-manager
        - --config-file=/etc/gardener-extension-provider-gcp/config/config.yaml
        - --infrastructure-max-concurrent-reconciles={{ .Values.controllers.infrastructure.concurrentSyncs }}
        - --infrastructure-ignore-operation-annotation={{ .Values.controllers.infrastructure.ignoreOperationAnnotation }}
        - --worker-max-concurrent-reconciles={{ .Values.controllers.worker.concurrentSyncs }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --disable-webhooks={{ .Values.disableWebhooks | join "," }}
        - --webhook-config-mode=service
        - --webhook-config-name=gcp-webhooks
        - --webhook-config-namespace={{ .Release.Namespace }}
        - --webhook-config-service-selectors={"app.kubernetes.io/name":"gardener-extension-provider-gcp","app.kubernetes.io/instance":"{{ .Release.Name }}"}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: webhook-server
          containerPort: 7890
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /etc/gardener-extension-provider-gcp/config
        - name: cert
          mountPath: /tmp/cert
      volumes:
      - name: config
        configMap:
          name: gardener-extension-provider-gcp-configmap
          defaultMode: 420
      - name: cert
        secret:
          secretName: gcp-webhooks
          defaultMode: 420
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-webhooks
  namespace: {{ .Release.Namespace }}
