---
apiVersion: core.gardener.cloud/v1alpha1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  deployment:
    type: helm
    providerConfig:
      chart: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOxZW2/bNhTOM3/FWfKyBRMt+ZIMBvaQOV5XIEuDuAiwp4KmjmU2FEmQlFM38377IMmyFbtwnHpN0MzfgyQfUTw3ngvphNkYFdoAP3lUTmgVaBdwbVG7Rm/MrKdTlsqDXRCGYXja6RT3MAxX72GzdXoQtdrN6CQMT1vRQRidnIatAwh34rolMueZPQh35rWq3HcCZsQN2tzvXZhEhBmz+HkY0fCQxOi4FcYXpDP4A2UKPF8XMNIW/BjhzXwJQU9bfDeAnlaeiZxwIVT2CRYriyiWYhc2LTkyqbiHNKIheWnzvHpsjP8Jkxm6nRPAo/Hfbq7E/2nU6uzj/zkgUpZglwBYNNoJr+20C5jRhFsqdGOxPIzVH5H7BaGxMYoBPEu6IJlH5wmAyaS80lLwaRfeji61v7LoUHlCLDqdWY6uC/czQrhWPLMWlR9MFXdd6OxTwDfFxvj3mJrCh40YjdTTFNXXtAOPxH+zFbYexn+zGUbtffw/B+r1nxnjGpOI3AoVd+F84XKSomcx8yzPE1vU8HKQM4xjF+7vgV6jROaQXlZkmM0IgGRDlC6fFHLe9DYbolXo0eWpZytGAGOUKXXjRtGTbDF+nZFQzjP1JVlzMZ1BPs+PUnDmylE3ZWWcE3s6U77UyaFE7rUttUqZ5+OLmpo7KPp00QGqAJ5LU3NjDvlAsJ1E+xrhACrbFs9oJ4LjGee5MS+3ZcyrZnOhR7DdEi1Rlj84rPm0INFlOYTZrLv22rMEZrPDh/Nc1arc2hfLElhpX4qfpkzFSx8E8FhlrcYFwbJYBi6vlr/WmK4U0jpPVJM6v9JaF/2z8/71h/5Fv/f+7bvLD5dnf/YHV2e9/mIkQNEO/m512q0RAUYCZXyNo4fUOf2K+XF3sfLoIjEsxi4bgNrn9/cBeP0XS2Ut1Obj4G9QQsWoPETNXK+XTqHfNbas/3bI+FfvAx6r/+0oWqn/Yae93/8/C4IgIPUeoHA0y/xYW/GZ5bt+evtLkc4XjUFPZs6jvdYSn94ZfBc132Yyz0cBMCPeWJ2ZQuBgeZLhaMWTcqmzmKzksQC0Qcu8UImbOo8p12okErfhVcN55rN8xATtcD5Lgr64S+HKh7u8oSiezOIpMzHzuC7t4eG6WA65Rb89F24xn7vGZsl7K4aldikzpe44QbXKfs7j6dNV74q2cm72yu+BRBbnSyJvx4RWX9b4btWINe12CozfhIqFSl5rfGiJ84Jf+WyDgQjAeuLYyhwuG35E7otQLKcYPOgS/8vtyEsn4hfClvV/3p2z0u5P7AQeO/9rt8PV/f9JJ9rX/+fAyvn/F6Ps/7z9f2n/fGtsjH+aW1ckSlvchcdj8d9pnqyd/0f7+H8WHMEV8x6tcuA1lL6GuzEqGGZC5j0MGMZvWYKOkiN4PxYOXGaMtt6BG6OUkEg9LE+6hEp+BouSeTHBvI8a1+hMxeQIFCZFbwA/Gosj8QljuBN+DD/8ROGdklPQqvgyFwkMWpBCISX0fPBh4LVFcgQ9naZawU1vALGwjtBE+EZxLcUndPjZNoprRRgnjfxS/XQT1VhONGT8NjMwEhIdOabuzpBjOmS35Jj61JDjf8gR3DArdObg7XnfETr/M4RQESNrlOOs/kjoxHEdY+PVZ4099tjjNeDfAAAA//92zR/SACQAAA==
      values:
        image:
          tag: 0.1.0-dev
