image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}

controllers:
  controlplane:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
    ignoreOperationAnnotation: false
  worker:
    concurrentSyncs: 5

disableControllers:
- controlplane-controller
disableWebhooks:
- controlplane
- controlplaneexposure
- controlplanebackup

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

config:
  machineImages:
  - name: coreos
    version: 2023.5.0
    regions:
    - name: eu-central-1
      ami: ami-012abdf0d2781f0a5
    - name: eu-west-1
      ami: ami-01f5fbceb7a9fa4d0
    - name: us-east-1
      ami: ami-08e58b93705fb503f
    - name: us-east-2
      ami: ami-03172282aaa2899be
    - name: ap-southeast-1
      ami: ami-0f8a9aa9857d8af7e
    - name: ap-southeast-2
      ami: ami-0e87752a1d331823a
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 80Gi
    backup:
      schedule: "0 */24 * * *"

gardener:
  seed:
    provider: aws
