image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

controllers:
  controlplane:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
    ignoreOperationAnnotation: false
  worker:
    concurrentSyncs: 5

disableControllers:
- controlplane-controller
disableWebhooks:
- controlplane
- controlplaneexposure
- controlplanebackup

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

config:
  machineImages:
  - name: coreos
    version: 1967.5.0
    regions:
    - name: eu-central-1
      ami: ami-0f46c2ed46d8157aa
    - name: eu-west-1
      ami: ami-0628e483315b5d17e
    - name: us-east-1
      ami: ami-0c6731558e5ca73f6
    - name: us-east-2
      ami: ami-05df30c25dffa0eaf
    - name: ap-southeast-1
      ami: ami-07739b17529e8c1d0
    - name: ap-southeast-2
      ami: ami-02d7d488d701a460e
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 80Gi
    backup:
      schedule: "0 */24 * * *"
