apiVersion: v1
kind: ServiceAccount
metadata:
  name: os-coreos
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: os-coreos
    helm.sh/chart: os-coreos
    app.kubernetes.io/instance: {{ .Release.Name }}
