apiVersion: v1
kind: Secret
metadata:
  name: csi-diskplugin-packet
  namespace: kube-system
data:
  apiToken: {{ index .Values.credential.apiToken }}
  projectID: {{ index .Values.credential.projectID }}
type: Opaque
