---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-provider-local
  labels:
    app.kubernetes.io/name: gardener-extension-provider-local
    helm.sh/chart: gardener-extension-provider-local
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  - infrastructures
  - infrastructures/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - provider-local-leader-election
  verbs:
  - get
  - watch
  - update
  - patch
- apiGroups:
  - ""
  - batch
  - rbac.authorization.k8s.io
  resources:
  - events
  - secrets
  - configmaps
  - serviceaccounts
  - rolebindings
  - jobs
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-extension-provider-local
  labels:
    app.kubernetes.io/name: gardener-extension-provider-local
    helm.sh/chart: gardener-extension-provider-local
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-extension-provider-local
subjects:
- kind: ServiceAccount
  name: gardener-extension-provider-local
  namespace: {{ .Release.Namespace }}
