{{- if eq .Values.gardener.seed.provider "azure" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: managed
{{- end }}
